name: Notebooks
on:
  pull_request:
    branches:
      - master
jobs:
  run_notebooks:
    name: Notebook runner
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -r dev_requirements.txt
          pip install -r notebook_requirements.txt
          pip install .
          ipython kernel install --name "python3" --user
      - name: Run notebooks
        run: |
          python -m allensdk.internal.notebooks.execute_notebooks \
            --notebooks_dir doc_template/examples_root/examples/nb \
            --skip_notebooks behavior_ophys_session.ipynb
      - name: Commit and push updated notebooks
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update notebooks
          push_options: --force
          file_pattern: '*.ipynb'
